[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  functions = "netlify/functions"
  publish = "."
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 